services:
  db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: osso
    volumes:
      - pg_data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  target:
  pg_data: